# Available modules: Core, FFA
modules:
  - "Core"
#  - FFA
discord: "https://discord.prismarine.xyz/"
store: "https://store.prismarine.xyz/"
rules:
  - "<red>Rules:"
  - "<gray>1. <gradient:red:gold>Respect all players"
  - "<gray>2. <gradient:red:gold>No Cheating/Hacking"
  - "<gray>3. <gradient:red:gold>No Advertising"
  - "<gray>4. <gradient:red:gold>No excessive spamming"
  - "<gray>5. <gradient:red:gold>No sharing personal information"

messages:
  quit: "<gradient:#ff5555:#ffb86c>←"
  join: "<gradient:#50fa7b:#8be9fd>➜"
  noperms: "<gradient:#ff5555:#ffb86c>No permission!</gradient>"
  invalid: "<gradient:#ff5555:#ffb86c>Missing/Invalid arguments or not supported!</gradient>"
  discord: "<gradient:#50fa7b:#8be9fd>Discord: "
  store: "<gradient:#df8e1d:#ea76cb>Store: "
  alert: "<gradient:#bd93f9:#ff79c6>Alert</gradient> <gray>»</gray> "
  day: "<#f1fa8c>Set the time to Day"
  night: "<#6272a4>Set the time to Night"
  feed: "<#ffb86c>Hunger saturated!"
  heal: "<#ff5555>Health restored!"
  fly: "<#04a5e5>Flight "
  player: "<#7287fd>Player "
  gave: "<#ea76cb>Gave "
  gamemode: "<#ea76cb>"
  staff:
    prefix: "<#40a02b>[STAFF] "
  teleported: "<#ea76cb>Teleported"
  lag: "<gradient:#50fa7b:#8be9fd>Status: "
  ping: "<gradient:#df8e1d:#dc8a78>Ping"
  msg:
    from: "<gradient:#e64553:#fe640b>From "
    to: "<gradient:#e64553:#fe640b>To "
    noreply: "<gradient:#ff5555:#ffb86c>You have noone to reply to!</gradient>"
  freeze:
    frozen: "<gradient:#ff5555:#ffb86c>\n             ⚠ You have been frozen! ⚠\n       <reset><gradient:#ff5555:#ffb86c>Do not log out, wait for a staff member.\n"
    unfrozen: "<#50fa7b>You have been unfrozen."
  speed:
    fly: "<#04a5e5>Flight speed set to "
    walk: "<#04a5e5>Walk speed set to "
  reboot: "<gradient:#ff5555:#ffb86c>Server is rebooting in "
  mutechat:
    muted: "<gradient:#ff5555:#ffb86c>Chat has been muted!"
    unmuted: "<#50fa7b>Chat has been unmuted!"
  vanish:
    vanished: "<#ff5555>You have vanished!"
    unvanished: "<#50fa7b>You have unvanished!"
  restarting: "<gradient:#ff5555:#ffb86c>Server is restarting"