name: PrismCore
version: '${project.version}'
main: org.prismcore.Core
authors: [ pixelNightly ]
contributors: [ ChatGPT ]
description: CorePlugin with Staff Commands, Messages, Chat, Punishments and more!
website: https://github.com/pog5/PrismCore
dependencies:
  server:
    ProtocolLib:
      load: AFTER
      required: true
      join-classpath: true
load: STARTUP
api-version: '1.20'