name: Core
version: '${project.version}'
main: org.core.Core
authors: [ pixelNightly ]
contributors: [ ChatGPT ]
description: Main Plugin
website: pog5.me
dependencies:
  server:
    ProtocolLib:
      load: AFTER
      required: true
      join-classpath: true
load: STARTUP
api-version: '1.20'